### ISSUE TITLE
When will the RSRD dataset be ready for release?

### ISSUE THREAD

**Issue by Yu-Cheung** [ztsrxh/RSRD_dev_kit#1]
Hi !
Thank you very much for this dataset, it helped me a lot in my research. Can you tell me when you will be able to release this dataset? Thanks!

**Comment by HuanyuanZhou** [comment]
Same question.
Wating for this dataset  be released !

**Comment by ztsrxh** [comment]
Thanks for your interest in our work. To have a quick preview of the dataset, please contact me at zhaot20@berkeley.edu
